name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Deployment Script
      run: |
        chmod +x deployment/deploy.sh
        ./deployment/deploy.sh
